version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - KEYCLOAK_URL=http://keycloak:8080/auth
      - KEYCLOAK_REALM=my-realm
      - KEYCLOAK_CLIENT=my-client
      - KEYCLOAK_SECRET=my-client-secret 
    depends_on:
      - minio
      - keycloak
    networks:
      - app-network

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - "9000:9000"
    command: server /data
    volumes:
      - minio_data:/data
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8080:8080"
    command:
      - start-dev
    networks:
      - app-network

volumes:
  minio_data:

networks:
  app-network:
    driver: bridge
